### ISSUE TITLE
Dependency python-Jose appears to be unmaintained

### ISSUE THREAD

**Issue by jusdino** [okta/okta-jwt-verifier-python#54]
Hey - just a heads-up that it appears this library is using `python-jose` as a dependency, which hasn't been updated in ~2 years. Maintainers haven't shown any activity in GitHub for issues or pull requests in quite a while, either. It would probably be prudent to pivot to PyJWT or JWCrypto, before CVEs start cropping up against the abandoned library.

**Comment by lewisdoesstuff** [comment]
> before CVEs start dropping up against the abandoned library.

Looks like that's now, found in [python-ecdsa](https://github.com/tlsfuzzer/python-ecdsa/security/advisories/GHSA-wj6h-64fc-37mp).

Are there any plans to use the `cryptography` build of `python-jose`, or migrate?

**Comment by rsb177** [comment]
@bretterer any updates on this?  Does Okta have a migration plan?  Or should we switch to a new library altogether?

**Comment by lewisdoesstuff** [comment]
Yet more vulnerabilities discovered in `python-jose`. 

We could _really_ do with a PyJWT build of this

**Comment by developingAlex** [comment]
It looks like the implementation mitigates this vulnerability (at least from what I looked into for the AccessTokenVerifier)
since calling `verify_access_token` it will [assert that the supplied header algorithm is set to RS256](https://github.com/okta/okta-jwt-verifier-python/blob/cb4e6780c55c234690299fa4ccef5ad33746c2c2/okta_jwt_verifier/jwt_verifier.py#L89-L90) (NOT HS256 which is the dangerous one) and raises a JWTValidationException if it finds it set to anything other than that.

**Comment by lukehsiao** [comment]
@developingAlex which vulnerability are you looking at exactly? There are a few. For example https://github.com/mpdavis/python-jose/issues/344 is https://github.com/advisories/GHSA-cjwg-qfpm-7377, and as far as I understand, is not necessarily related to the algorithm chosen.

**Comment by developingAlex** [comment]
Sorry I was referring only to [this python-jose issue description](https://github.com/mpdavis/python-jose/issues/346).
